version: '3.8'

services:
  client:
  #check build
    build: client/
    volumes:
      - ./client:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true # Ensure hot-reloading works in Docker
